language: node_js
os: windows

git:
  depth: 3

branches:
  except:
  - legacy
  - experimental

branches:
  only:
  - master
  - main
  - stable

before_install:
  - python

install:
  - yarn install

scripts:
  - yarn deploy
  - yarn test

before_script:
  - yarn test

after_scripts:
  - yarn clean

cache:
  directories:
    -node_modules

jobs:
  include:
    - stage: test
      script: yarn test
      script: yarn eslint
    - stage: deploy
      script: yarn deploy

deploy:
  provider: heroku
  on
    repo: pedroesc/platzi-store
